
services:
  airflow:
    container_name: custom_airflow
    build: .
    ports:
      - 8080:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    command: >
      bash -c "airflow db migrate && airflow standalone"
    user: "0:0"
    networks:
      - netnet
    group_add:
      - '1001'
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
      
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    volumes:
      - ./postgres-db-volume:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - netnet

networks:
  netnet:
    driver: bridge