FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir lightning==2.5.0
RUN pip install --no-cache-dir psycopg2-binary sqlalchemy
RUN pip install --no-cache-dir minio s3fs
RUN pip install --no-cache-dir boto3

COPY movie_recommender movie_recommender
COPY training/dlrm.py train_dlrm.py


ENV CUDA_VISIBLE_DEVICES=0

CMD ["python","train_dlrm.py"]