# TODO use a different image
FROM pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir psycopg2-binary sqlalchemy
RUN pip install --no-cache-dir xgboost
RUN pip install --no-cache-dir minio optuna s3fs
RUN pip install --no-cache-dir boto3
RUN pip install --no-cache-dir --upgrade aiobotocore botocore boto3

COPY movie_recommender movie_recommender
COPY training/simsearch.py train_simsearch.py


ENV CUDA_VISIBLE_DEVICES=0