services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: mydb

    volumes:
      - ./vlms/database:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - net
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
    driver: bridge
